# SLIM makefile for the 'networking' package.

PKG = networking
VER =
GET = NOOP
URL =
PRG =
TGZ =
SRC =
DST =

LICENSE  = GPL
LICFILE  =
UPSTREAM =
BINARIES =
PROVIDES =
CATEGORY = networking

PREP_DEPEND =
BUILD_DEPEND =
INSTALL_DEPEND =

DESCRIPTION = This package arranges to bring up all the network \
interfaces at boot time.

fetch:
unpack:
prep:
build:
stage:
install:
	$(Q) $(start) -n 200 -f networking.init

clean:
distclean: clean

include depend.mk
